# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # do not allow a build to run for more than 10 minutes
    timeout-minutes: 10
    # Use the latest version of Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: ["3.10"]
        os: [ubuntu-latest]
    # Define the workflow steps
    steps:
    # Checkout the code of the repository
        - name: Check out Repository Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        # Setup Python for the current language version
        - name: Setup Python ${{ matrix.python-version }}
          if: always()
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        # Install pip
        - name: Install Pip
          if: always()
          run: |
            pip install -U pip
            python -m pip install --user pipx
        # Run the Python programs
        - name: Run Python Programs
          if: always()
          run: |
            python source/question_one.py
            python source/question_two.py
            python source/question_three.py
            python source/question_four.py
            python source/question_five.py
        # Run GatorGrader: uses the decrypted version of config/gatorgrade.yml
        - name: Run GatorGrader with GatorGrade
          if: always()
          env:
            GATORGRADE_GPG_PASSPHRASE: ${{ secrets.GATORGRADE_GPG_PASSPHRASE }}
          run:  |
           mkdir config
           gpg --version
           gpg --quiet --batch --yes --decrypt --passphrase="$GATORGRADE_GPG_PASSPHRASE" --output config/gatorgrade.yml vault/gatorgrade.yml.gpg
           pipx install gatorgrade
           gatorgrade --config config/gatorgrade.yml --report env md GITHUB_STEP_SUMMARY
